# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 651e8c369a7fa79325e9bbb3d80ee0a062a3af64c4b841a7e16932a2758acbca96a77732af19c1e7d81ad34608fcb52e90864b8078aa34f3bb4df860197bea7b

test:
  secret_key_base: 42787ded24831cea01bd50c807ddd5792e9dc34d5169384454969566623981635479bdff5fecf0c8d40592eb57940606e014ec1d2235b5ff45c8676f318be4cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
